# Generated by Django 5.0.4 on 2024-04-23 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('rule_type', models.CharField(max_length=20, verbose_name='team')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_x_1', to='puzzles.rule')),
                ('x2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_x_2', to='puzzles.rule')),
                ('x3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_x_3', to='puzzles.rule')),
                ('y1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_y_1', to='puzzles.rule')),
                ('y2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_y_2', to='puzzles.rule')),
                ('y3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_y_3', to='puzzles.rule')),
            ],
        ),
    ]
