# Generated by Django 5.0.4 on 2024-05-06 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='x1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puz_x_1', to='puzzles.rule'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='x2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puz_x_2', to='puzzles.rule'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='x3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puz_x_3', to='puzzles.rule'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='y1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puz_y_1', to='puzzles.rule'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='y2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puz_y_2', to='puzzles.rule'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='y3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puz_y_3', to='puzzles.rule'),
        ),
        migrations.CreateModel(
            name='GeneratedPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('x1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_puz_x_1', to='puzzles.rule')),
                ('x2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_puz_x_2', to='puzzles.rule')),
                ('x3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_puz_x_3', to='puzzles.rule')),
                ('y1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_puz_y_1', to='puzzles.rule')),
                ('y2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_puz_y_2', to='puzzles.rule')),
                ('y3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_puz_y_3', to='puzzles.rule')),
            ],
        ),
    ]
