# Generated by Django 5.0.4 on 2024-05-07 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_alter_puzzle_x1_alter_puzzle_x2_alter_puzzle_x3_and_more'),
        ('rules', '0009_add_crosses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='y3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puz_y_3', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='x3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puz_x_3', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='generatedpuzzle',
            name='y3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_puz_y_3', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='generatedpuzzle',
            name='x3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_puz_x_3', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='x1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puz_x_1', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='generatedpuzzle',
            name='x1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_puz_x_1', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='y1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puz_y_1', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='x2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puz_x_2', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='generatedpuzzle',
            name='x2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_puz_x_2', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='y2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puz_y_2', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='generatedpuzzle',
            name='y1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_puz_y_1', to='rules.rule'),
        ),
        migrations.AlterField(
            model_name='generatedpuzzle',
            name='y2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_puz_y_2', to='rules.rule'),
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
