# Generated by Django 5.0.4 on 2024-05-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_alter_puzzle_y3_alter_puzzle_x3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedPuzzle',
        ),
    ]
