# Generated by Django 5.0.4 on 2024-05-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_delete_generatedpuzzle'),
        ('rules', '0009_add_crosses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='x1',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='x3',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='y1',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='y2',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='y3',
        ),
        migrations.CreateModel(
            name='PuzzleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.TextField(choices=[('x', 'X'), ('y', 'Y')], max_length=1)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assoc_rules', to='puzzles.puzzle')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assoc_puzzles', to='rules.rule')),
            ],
        ),
    ]
