# Generated by Django 5.0.4 on 2024-05-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_remove_puzzle_x1_remove_puzzle_x2_remove_puzzle_x3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlerule',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
