# Generated by Django 5.0.4 on 2024-04-23 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeralternatename',
            name='player_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_names', to='players.player'),
        ),
    ]
