# Generated by Django 5.0.4 on 2024-05-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_age_alter_player_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
