# Generated by Django 5.0.4 on 2024-05-11 07:58
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_load_player_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=True),
        )
    ]
