# Generated by Django 5.0.4 on 2025-02-20 00:03

from django.db import migrations

def load_update_2502():
    with open('db_data/update/2502/players/update.sql', 'r+', encoding='utf-8') as f:
        data = f.read()
    if data is None:
        return ""
    return data

def load_update_reverse_2502():
    with open('db_data/update/2502/players/update_reverse.sql', 'r+', encoding='utf-8') as f:
        data = f.read()
    if data is None:
        return ""
    return data

class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_add_active_flag'),
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(load_update_2502(), reverse_sql=load_update_reverse_2502())
    ]
