# Generated by Django 5.0.4 on 2025-02-20 00:03

from django.db import migrations


def load_update():
    with open("db_data/update/250917/players/update.sql", "r+", encoding="utf-8") as f:
        data = f.read()
    if data is None:
        return ""
    return data


def load_update_reverse():
    with open("db_data/update/250917/players/reverse.sql", "r+", encoding="utf-8") as f:
        data = f.read()
    if data is None:
        return ""
    return data


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0009_update_250916"),
        ("meta", "0001_initial"),
        # ('rules', '0003_alter_rule_add_active_flag'),
    ]

    operations = [migrations.RunSQL(load_update(), reverse_sql=load_update_reverse())]
