# Generated by Django 5.0.4 on 2025-02-20 02:29

from sqlite3 import IntegrityError
from django.db import migrations, models, transaction
from datetime import datetime

def make_meta(apps, schema_editor):
    DataUpdate = apps.get_model("meta", "DataUpdate")
    for app in ["players", "teams", "rules"]:
        try:
            with transaction.atomic():
                meta = DataUpdate()
                # meta.data_update_date = datetime.today().strftime('%Y-%m-%d')
                meta.date = '2024-05-14'
                meta.app = app
                meta.save()
        except IntegrityError:
            meta.delete()

def delete_deta(apps, schema_editor):
    DataUpdate = apps.get_model("meta", "DataUpdate")
    meta = DataUpdate.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('app', models.CharField(max_length=32)),
            ],
        ),
        migrations.RunPython(make_meta, reverse_code=delete_deta)
    ]
