# Generated by Django 5.0.4 on 2025-02-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_becomes_alter_team_came_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='short',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
