# Generated by Django 5.0.4 on 2025-09-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_update_250916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamalternatename',
            name='alternate_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamsisterteam',
            name='sister_team_name',
            field=models.CharField(max_length=100),
        ),
    ]
