# Generated by Django 5.0.4 on 2025-02-21 06:32

from django.db import migrations

def load_update():
    with open('db_data/update/250917/teams/update.sql', 'r+', encoding='utf-8') as f:
        data = f.read()
    if data is None:
        return ""
    return data

def load_update_reverse():
    with open('db_data/update/250917/teams/reverse.sql', 'r+', encoding='utf-8') as f:
        data = f.read()
    if data is None:
        return ""
    return data

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_teamalternatename_alternate_name_and_more'),
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(load_update(), reverse_sql=load_update_reverse())
    ]
