# Generated by Django 5.0.4 on 2025-03-17 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_update_250313'),
        ('pro2pro', '0002_initial_roster_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterlink',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_links', to='players.player'),
        ),
        migrations.AlterField(
            model_name='rosterlink',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_links', to='pro2pro.roster'),
        ),
    ]
