# Generated by Django 5.0.4 on 2024-05-07 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0005_load_player_data'),
        ('puzzles', '0004_delete_generatedpuzzle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_roster', to='puzzles.puzzle')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=64)),
                ('remaining_guesses', models.IntegerField(default=10)),
                ('guess_11', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses_11', to='players.player')),
                ('guess_12', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses_12', to='players.player')),
                ('guess_13', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses_13', to='players.player')),
                ('guess_21', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses_21', to='players.player')),
                ('guess_22', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses_22', to='players.player')),
                ('guess_23', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses_23', to='players.player')),
                ('guess_31', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses_31', to='players.player')),
                ('guess_32', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses_32', to='players.player')),
                ('guess_33', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses_33', to='players.player')),
                ('rostered_puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.gameroster')),
            ],
            options={
                'unique_together': {('rostered_puzzle', 'sessionid')},
            },
        ),
    ]
