# Generated by Django 5.0.4 on 2024-05-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finalised',
            field=models.CharField(default='in_progress', max_length=20),
        ),
    ]
