# Generated by Django 5.0.4 on 2024-05-11 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroster',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_roster', to='puzzles.puzzle'),
        ),
        migrations.AddField(
            model_name='game',
            name='rostered_puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.gameroster'),
        ),
        migrations.AlterUniqueTogether(
            name='gameguess',
            unique_together={('game', 'slot')},
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('rostered_puzzle', 'sessionid')},
        ),
    ]
