# Generated by Django 5.0.4 on 2024-05-07 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_finalised_game_status'),
        ('players', '0005_load_player_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='guess_11',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guess_12',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guess_13',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guess_21',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guess_22',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guess_23',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guess_31',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guess_32',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guess_33',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('finalised', 'Finalised')], max_length=20),
        ),
        migrations.CreateModel(
            name='GameGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='players.player')),
            ],
            options={
                'unique_together': {('game', 'slot')},
            },
        ),
    ]
