# Generated by Django 5.0.4 on 2024-05-07 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_guess_11_remove_game_guess_12_and_more'),
        ('players', '0005_load_player_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameguess',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='players.player'),
        ),
    ]
