# Generated by Django 5.0.4 on 2024-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gameguess_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('finalised', 'Finalised')], default='in_progress', max_length=20),
        ),
    ]
