# Generated by Django 5.0.4 on 2024-05-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameguess',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
