# Generated by Django 5.0.4 on 2024-05-02 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0005_load_player_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('rule_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RuleValidPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valid_player', to='players.player')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valid_rule', to='rules.rule')),
            ],
        ),
    ]
