# Generated by Django 5.0.4 on 2024-05-11 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0005_load_player_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('rule_type', models.CharField(max_length=50)),
                ('valid_players', models.ManyToManyField(related_name='valid_rules', to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='ValidCrosses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crosses', models.ManyToManyField(related_name='valid_crosses', to='rules.rule')),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule_cross', to='rules.rule')),
            ],
        ),
    ]
