# Generated by Django 5.0.4 on 2024-05-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_load_player_data'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='valid_players',
            field=models.ManyToManyField(related_name='valid_player', to='players.player'),
        ),
        migrations.DeleteModel(
            name='RuleValidPlayer',
        ),
    ]
