# Generated by Django 5.0.4 on 2024-05-11 07:58
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_add_rules_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='active',
            field=models.BooleanField(default=True, db_default=True),
        )
    ]
