# Generated by Django 5.0.4 on 2024-05-03 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_load_player_data'),
        ('rules', '0002_rule_valid_players_delete_rulevalidplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TieredValidPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.ManyToManyField(related_name='primary_valid_players', to='players.player')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vp_rule', to='rules.rule')),
                ('secondary', models.ManyToManyField(related_name='secondary_valid_players', to='players.player')),
            ],
        ),
    ]
