# Generated by Django 5.0.4 on 2024-05-03 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_tieredvalidplayers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='valid_players',
        ),
    ]
