# Generated by Django 5.0.4 on 2024-05-03 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_remove_rule_valid_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tieredvalidplayers',
            name='rule',
        ),
        migrations.AddField(
            model_name='rule',
            name='valid_players',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.tieredvalidplayers'),
        ),
    ]
