# Generated by Django 5.0.4 on 2024-05-03 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_remove_tieredvalidplayers_rule_rule_valid_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='valid_players',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valid_playerz', to='rules.tieredvalidplayers'),
        ),
    ]
